# Generated by Django 2.2.6 on 2019-11-14 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191004_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='rate_count',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='rate_summary',
        ),
        migrations.AddField(
            model_name='visitor',
            name='rated_lectors',
            field=models.ManyToManyField(related_name='rated_by_visitors', to='accounts.Lector'),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(choices=[(1, 'AWFUL'), (2, 'BAD'), (3, 'GOOD'), (4, 'NICE'), (5, 'AMAZING')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='accounts.Lector')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='accounts.Visitor')),
            ],
        ),
    ]
