# Generated by Django 2.2.6 on 2019-11-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191114_1605'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('visitor', 'lector')},
        ),
    ]
