# Generated by Django 2.2.6 on 2019-11-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191114_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='rated_lectors',
        ),
    ]
