# Generated by Django 2.2.6 on 2019-11-19 16:58
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_remove_visitor_rated_lectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_lector',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rate',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lector_rates',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rate',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_rates',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Lector',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
