# Generated by Django 2.2.6 on 2019-12-03 18:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20191201_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('query_params', django.contrib.postgres.fields.jsonb.JSONField()),
                ('response_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('response_status', models.PositiveSmallIntegerField()),
                ('expires_after', models.DateTimeField()),
            ],
        ),
    ]
