# Generated by Django 2.2.6 on 2019-11-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20191102_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='following_meetings', to='accounts.User'),
        ),
    ]
